service: first-example

provider:
  name: aws
  runtime: nodejs4.3

functions:
  create:
    handler: handler.getTrackingInfo
    events:
      - http:
          path: /{id}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                id: true
